### ISSUE TITLE
details

### ISSUE THREAD

**Issue by arita37** [rhrlima/ge-cnn#1]
Hello,

This project looks intersting.
Is there a way to discuss ?

**Comment by rhrlima** [comment]
Hi,

This is an ongoing project I'm working on my PhD. This public repository will be updated as soon as I develop the private version.

Feel free to ask anything, I'll do my best to help.

**Comment by arita37** [comment]
Hello,
Can we chat here ?
https://gitter.im/python-DL2/community#

**Comment by rhrlima** [comment]
I joined the chat.
